SELECT ndt.*, 
       ndh.*, 
       cm.COMPANY_ID,
       ro.RPTOWNERNAME,
       ro.RPTOWNER_RELATIONSHIP,
       ro.RPTOWNER_TITLE
FROM VERDAD.INSIDER_TRADING.NONDERIV_TRANS AS ndt
JOIN VERDAD.INSIDER_TRADING.NONDERIV_HOLDING AS ndh 
    ON ndt.ACCESSION_NUMBER = ndh.ACCESSION_NUMBER
JOIN VERDAD.INSIDER_TRADING.SUBMISSION AS sub 
    ON ndt.ACCESSION_NUMBER = sub.ACCESSION_NUMBER
JOIN VERDAD.INSIDER_TRADING.CIK_MAPPING AS cm 
    ON sub.ISSUERCIK = cm.CIK_ID
JOIN VERDAD.INSIDER_TRADING.REPORTINGOWNER AS ro 
    ON ndt.ACCESSION_NUMBER = ro.ACCESSION_NUMBER
WHERE cm.COMPANY_ID IN (
    SELECT COMPANY_ID 
    FROM BIOTECH_PROJECT.INTERNS.BIOTECH_FACTORS
);